### ISSUE TITLE
Investigate Node vs C# server resource usage, web socket limitations

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext#10]
As an architect, I want to know how well Node would suit us as a web server technology as opposed to C# to determine if we should use a C# web server or Node web server (assuming we do not go with Electron-Edge as referenced in #9).

- **Are we limiting ourselves using Node websocket as opposed to a C# websocket?**
- **How do startup and resource use look between C# and Node?**

**Comment by tjcouch-sil** [comment]
Express:
Takes virtually zero time to start
Uses 38.6 MB memory

ASP.NET:

**Comment by irahopkinson** [comment]
@tjcouch-sil I asssume the above results are on Win 10? Do we see similar results on Linux and MacOS? Using WSL2 or dual boot to Linux would be a fair comparison since its the same machine but I'm not sure how you make the comaprison on MacOS. We need to be continually thinking x-platform, perhaps we should determine a way to make a fair comparison.

**Comment by tjcouch-sil** [comment]
@irahopkinson Yes, that was in Windows 10. Good clarification. I don't have the experience with WSL2 to do much with Linux right now. Maybe we can investigate those further another time. Looks like the electron-edge-js test was successful enough that the startup time will not be that significant a difference (server startup time would affect websocket communication with external executables like FLEx, but internal apis do not need to wait on the server if we use edge as everything is passing through electron ipc and edge).
