### ISSUE TITLE
Create a Shared Drive

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext#14]
Under what organization is our shared drive? SIL? Other? Who has to take the expense of hosting files? Will SIL always be willing to pay? Does that create any weirdness ownership-wise? Who has access if SIL creates it?

Create shared drive.

**Comment by darren8c** [comment]
We have two groups for Paratext
  paratext-dev@groups.sl.org
  paratext-dev-team@googlegroups.com

I propose we ask TechOps to create 2 google groups @googlegroups.com
Since we are talking about a relatively small amount of data, and we are planning to build the "platform/core" I think SIL will pay, and will be happy to pay this going forward.

My sense of the BT Tools community is that this would not create any weirdness at all.  I would like to propose that starting out SIL (Glenn and I to start) will manage the membership of the team as usually we will be the first to have contact with orgs as they start to partner.  I think one organization has to own it so they can appoint admins and remove admins when people are no longer with the organization.  We can adjust in the future if needed, but I think this is our best option right now.

**Comment by darren8c** [comment]
I will ask TechOps to create the groups!

**Comment by FoolRunning** [comment]
@darren8c, I don't know that we've ever used the Paratext ones. I would suggest we not use a Google Group until we think there is a use for it.

**Comment by darren8c** [comment]
Getting Devs into discord is probably more useful.  I just created a Shared Drive as a place we can start to use, and will add people to it, as we connect and collaborate with them.
